runtime: python27
api_version: 1
threadsafe: False

handlers:
- url: /favicon.ico
  static_files: static/img/favico.gif
  upload: static/img/favico.gif

- url: /lib/static
  static_dir: static

- url: /static
  static_dir: content/static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: lib/admin.py
  login: admin

- url: /.*
  script: lib/mkomo.py

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
