application: mkomo
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favico.gif
  upload: static/img/favico.gif

- url: /static
  static_dir: static

- url: /admin/.*
  script: src/admin.py
  login: admin

- url: /.*
  script: src/mkomo.py
